MVC/SessionApp/SessionApp/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SessionApp.Controllers
{
    public class ApplicationController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC/SessionApp/SessionApp/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SessionApp.Controllers
{
    public class SessionController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC/SessionApp/SessionApp/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SessionApp.Controllers
{
    public class SummaryController : Controller
    {
        public ActionResult Summary()
        {
            return View();
        }
    }
}

MVC/SessionApp/SessionApp/Views/Application/Index.cshtml
@{

    if(Context.Application["count"]==null)
    {
        Context.Application["count"] = 0;
    }

    int oldCount = (int)Context.Application["count"];
    Context.Application["count"] = ((int) Context.Application["count"] + 1);

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h3>old: @oldCount</h3>
        <h3>new: @Context.Application["count"]</h3>
        @Html.ActionLink("Click Here To View Summary", "Summary", "Summary")
    </div>
</body>
</html>

MVC/SessionApp/SessionApp/Views/Session/Index.cshtml
@{
    if(Session["count"] == null)
    {
        Session["count"] = 0;
    }

    var old = (int) Session["count"];
    Session["count"] = ((int) Session["count"] + 1);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h3>old: @old</h3>
        <h3>new: @Session["count"]</h3>
        <h3>@Session.SessionID</h3>
        @Html.ActionLink("Click Here To View Summary", "Summary", "Summary")
    </div>
</body>
</html>