MVC/BankApp/BankApp/Controllers/AbcdBankAuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BankApp.Models;
using BankApp.Data;
using System.Security.Cryptography;
using System.Text;

namespace BankApp.Controllers
{
    public class AbcdBankAuthenticationController : Controller
    {
        IDataAccess bankDb;

        public AbcdBankAuthenticationController()
        {
            this.bankDb = new BankSqlDB();
        }

        public ActionResult Main()
        {
            return View();
        }
        public ActionResult Login()
        {
            if (Session["loggedInUser"] != null)
            {
                return RedirectToAction("Welcome", "AbcdBank");
            }

            return View(new BankUserModel());
        }

        [HttpPost]
        public ActionResult Login(BankUserModel bankuser)
        {
            if (!ModelState.IsValid)
            {
                return View(bankuser);
            }

            if(!bankDb.CheckNameExists(bankuser.Name))
            {
                bankuser.NameErrorMessage = "Invalid Username";
                return View(bankuser);
            }

            SHA1CryptoServiceProvider sha1 = new SHA1CryptoServiceProvider();
            byte[] passwordBytes = Encoding.ASCII.GetBytes(bankuser.Password);
            byte[] encryptedPasswordBytes = sha1.ComputeHash(passwordBytes);
            string encrptedPassword = Convert.ToBase64String(encryptedPasswordBytes);

            if (!bankDb.MatchPassword(bankuser.Name, encrptedPassword))
            {
                bankuser.PasswordErrorMessage = "Please Enter Correct Password";
                return View(bankuser);
            }

            Session["loggedInUser"] = bankuser.Name;
            return RedirectToAction("Welcome", "AbcdBank", bankuser);
        }

        public ActionResult Register()
        {
            return View(new RegistrationViewModel());
        }

        [HttpPost]
        public ActionResult Register(RegistrationViewModel rvm)
        {
            if(!ModelState.IsValid)
            {
                rvm.NameErrorMessage = "";
                return View(rvm);
            }


            if(bankDb.CheckNameExists(rvm.Name))
            {
                rvm.NameErrorMessage = "Username Already Exists" ;
                return View(rvm);
            }

            SHA1CryptoServiceProvider sha1 = new SHA1CryptoServiceProvider();
            byte[] passwordBytes = Encoding.ASCII.GetBytes(rvm.Password);
            byte[] encryptedPasswordBytes = sha1.ComputeHash(passwordBytes);
            string encrptedPassword = Convert.ToBase64String(encryptedPasswordBytes);

            //var hashPassword = rvm.Password.GetHashCode();
            bool registrationResult =  bankDb.RegisterBankUser(rvm.Name, rvm.Balance, encrptedPassword);

            if(!registrationResult)
            {
                rvm.RegisterSuccessMessage = "";
                rvm.RegisterErrorMessage = "Err!!! Something Went Wrong Pls Try Again";
                return View(rvm);
            }

            rvm.NameErrorMessage = "";
            rvm.RegisterSuccessMessage = "Registered Successfully Pls Login";
            return View(rvm);
        }
    }
}

MVC/BankApp/BankApp/Controllers/AbcdBankController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BankApp.Data;
using BankApp.Models;

namespace BankApp.Controllers
{
    public class AbcdBankController : Controller
    {
        // GET: AbcdBank
        IDataAccess bankDb;

        public AbcdBankController()
        {
            bankDb = new BankSqlDB();
        }

        public ActionResult Main()
        {
            if(Session["loggedInUser"]!=null)
            {
                return RedirectToAction("Welcome");
            }

            return View();

        }

        public ActionResult Welcome()
        {
            if(Session["loggedInUser"]==null)
            {
                return RedirectToAction("Main");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Logout()
        {
            Session["loggedInUser"] = null;
            return RedirectToAction("Main");
        }
        [HttpGet]
        public ActionResult DoTransaction()
        {
            if (Session["loggedInUser"] != null)
            {
                return View(new TransactionModel());
            }

            return RedirectToAction("Main");
            
        }

        [HttpPost]
        public ActionResult DoTransaction(TransactionModel transaction)
        {
            if(!ModelState.IsValid)
            {
                return View(transaction);
            }

            int balance = bankDb.GetBalance(Session["loggedInUser"].ToString());

            if(transaction.Type == "D")
            {
                transaction.AmountErrorMessage = "";
                balance = balance + transaction.Amount;
                bool transactionResult = bankDb.DoTransaction(Session["loggedInUser"].ToString(), balance, transaction.Type, transaction.Amount);
                
                if(transactionResult)
                {
                    transaction.Status = "Successfull";
                    return View(transaction);
                }


                transaction.Status = "Fail";
                return View(transaction);
            }


            if (transaction.Type == "W")
            {
                balance = balance - transaction.Amount;

                if(balance < 500)
                {
                    transaction.AmountErrorMessage = "Minimum Balance Must be 500";
                    return View(transaction);
                }

                transaction.AmountErrorMessage = "";
                bool transactionResult = bankDb.DoTransaction(Session["loggedInUser"].ToString(), balance, transaction.Type, transaction.Amount);
                
                if (transactionResult)
                {
                    transaction.Status = "Successfull";
                    return View(transaction);
                }

                transaction.Status = "Fail";
                return View(transaction);
            }
            transaction.AmountErrorMessage = "";
            transaction.Status = "";
            return Content("Fail");
        }

        public ActionResult ViewPassBook()
        {
            if (Session["loggedInUser"] == null)
            {
                return RedirectToAction("Main");
            }

            string passBookDetails = bankDb.GetTransactionDetails(Session["loggedInUser"].ToString());
            string[] passBookDetailsArr = passBookDetails.Split('\n');
            ViewBag.passBookString = passBookDetailsArr;
            return View();
        }

        [HttpPost]
        public ActionResult Export()
        {
            string passBookDetails = bankDb.GetTransactionDetails(Session["loggedInUser"].ToString());
            StringWriter sw = new StringWriter();

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment;filename=PassBookDetails.csv");
            Response.ContentType = "text/csv";

            sw.WriteLine(passBookDetails);
            
            Response.Write(sw.ToString());

            Response.End();

            return RedirectToAction("ViewPassBook");

        }

    }
}

MVC/BankApp/BankApp/Views/AbcdBank/DoTransaction.cshtml
@{
    ViewBag.Title = "DoTransaction";
    Layout = "~/Views/AbcdBank/MainMaster.cshtml";
}


<h2>DoTransaction</h2>

@model BankApp.Models.TransactionModel
@using (Html.BeginForm())
{
    <h3>@Model.Status</h3>
    <label>Name: @Session["loggedInUser"].ToString()</label>

    <div class="form-control">
        <label>
            Amount:
            @Html.TextBoxFor(m => m.Amount)
            <span style="color:red">@Html.ValidationMessageFor(m => m.Amount)</span>
            <span style="color:red">@Model.AmountErrorMessage</span>
        </label>
    </div>

    <div class="form-control">
        <label>
            @Html.RadioButtonFor(m => m.Type, "D") Depost
            <span style="color:red">@Html.ValidationMessageFor(m => m.Amount)</span>
        </label>

        <label>
            @Html.RadioButtonFor(m => m.Type, "W") Widthdraw
            <span style="color:red">@Html.ValidationMessageFor(m => m.Amount)</span>
        </label>
    </div>

    <div class="form-control">
        <button type="submit" class="btn-default">Add</button>
    </div>

}

MVC/BankApp/BankApp/Views/AbcdBank/Main.cshtml
@{
    ViewBag.Title = "Main";
    Layout = "~/Views/AbcdBank/MainMaster.cshtml";
}

<h2>Random Ads Goes Here</h2>

MVC/BankApp/BankApp/Views/AbcdBank/MainMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-default">

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink("AbcdBank", "Main")
                </li>
                <li>
                    @Html.ActionLink("Do Transaction", "DoTransaction")
                </li>
                <li>
                    @Html.ActionLink("View PassBook", "ViewPassBook")
                </li>
            </ul>

            @if (Session["loggedInUser"] != null)
            {

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Session["loggedInUser"].ToString()
                        </li>
                        <li>
                            @using (Html.BeginForm("Logout", "AbcdBank"))
                            {
                                <button class="btn btn-info">Log Out</button>
                            }
                        </li>
                    </ul>
                </div>
            }

            @if (Session["loggedInUser"] == null)
            {
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @using (Html.BeginForm("Login", "AbcdBankAuthentication"))
                            {
                                <button class="btn btn-info">Log In</button>
                            }
                        </li>
                    </ul>
                </div>
            }

        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>
</html>

MVC/BankApp/BankApp/Views/AbcdBank/ViewPassBook.cshtml
@{
    ViewBag.Title = "ViewPassBook";
    Layout = "~/Views/AbcdBank/MainMaster.cshtml";
}

<h2>PassBook</h2>

@foreach(string str in ViewBag.passBookString)
            {
                <p>@str</p>
            }

@using(Html.BeginForm("Export", "AbcdBank"))
            {
                <button class="btn-default">Export</button>
            }

MVC/BankApp/BankApp/Views/AbcdBank/Welcome.cshtml
@{
    ViewBag.Title = "LoginInSession";
    Layout = "~/Views/AbcdBank/MainMaster.cshtml";
}



 <h2>Welcome Back @Session["loggedInUser"].ToString()</h2>